server :
  port : 8120

api:
  json-place-holder:
    domain: 'jsonplaceholder.typicode.com'
    endpoints:
      users: '/users'
      posts: '/posts'
      comments: '/comments'
  
database:
  db-name: "jsonplace"

spring:
  datasource:
 #   primary:
 #   driverClassName: "com.mysql.cj.jdbc.Driver"
 #   url: "jdbc:mysql://localhost:3306/${database.db-name}"
 #   username: "root"
 #   password: "admin1234"
 #   secondary:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/${database.db-name}"
    username: "postgres"
    password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update
  # Hibernate ddl auto (create, create-drop, validate, update)

